// <auto-generated />
using System;
using Lab.Infrasturcture.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab.Infrasturcture.Migrations
{
    [DbContext(typeof(LabAppDbContext))]
    partial class LabAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Lab.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DiagnosisDetail")
                        .HasColumnType("longtext");

                    b.Property<string>("PatientAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("PatientDiagnosis")
                        .HasColumnType("longtext");

                    b.Property<string>("PatientEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("PatientName")
                        .HasColumnType("longtext");

                    b.Property<int>("PatientNumber")
                        .HasColumnType("int");

                    b.Property<string>("PatientPhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("PatientSurname")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReportNumber")
                        .HasColumnType("int");

                    b.Property<string>("ReportPicture")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
